image: java:8-jdk
services:
  - postgres:13-alpine
variables:
  POSTGRES_DB: mabase
  POSTGRES_HOST : localhost
  POSTGRES_PORT : 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
stages:
  - test
  - build
  - deploy
#build and test at each push
#Audit process
test:
  stage: test
  script:
    - echo "$CI_PIPELINE_CREATED_AT"
    - ./gradlew -x test
  after_script:
    - echo "$CI_JOB_STATUS"
    - echo "$CI_COMMIT_AUTHOR"
# Building process
build:
  stage: build
  script:
    # To generate the war file
    - echo "$CI_PIPELINE_CREATED_AT"
    - ./gradlew -x test build
    - cd build/libs
    - ls -lh
    - pwd
  artifacts:
    paths:
      - build/libs/*.war
  after_script:
    - echo "$CI_JOB_STATUS"
    - echo "$CI_COMMIT_AUTHOR"
#deploy on uat, all push on develop
#Deployment